### PR TITLE
feat: adding SonarQube to the project (#124)

### PR DESCRIPTION
**Pull request by Firassawan**
The purpose of this commit is to integrate the SonarQube tool into our project. The files added all relate to SonarQube.

### CODE REVIEW

**Comment by bkenza** [comment]
Can you please add a description on how we can test your PR?

**Comment by bkenza** [comment]
@Firassawan I've followed the exact instructions you provided on the wiki page, but I could not make it work. As you can see on the screenshot below, it says "**Started SonarQube.**". However, nothing is rendered on **http://localhost:9000/**.

image

I will try again tomorrow :)

**Comment by Firassawan** [comment]
@bkenza, You’re on the right track, the default port for SonarQube is usually 9000, if that port is busy then your machine might have assigned a different port. Please try Port 8080 or 9090. If that still doesn’t work, you can check the port assigned for SonarQube through your terminal.

**Comment by Firassawan** [comment]
Update: For Mac users, docker is needed for the SonarQube server to run properly. Ill update the Wiki.

**Comment by mohanadarafe** [comment]
In step 15, I get this error when running the command Sonnar generates for me:

```
Error during SonarScanner execution
org.sonar.java.AnalysisException: Please provide compiled classes of your project with sonar.java.binaries property
```

**Comment by bkenza** [comment]
In the login page, I get the following error: 
`authentication failed`

**Comment by bkenza** [comment]
**Update**:

@HussainWitwit was able to set up SonarQube on his computer! We will now be able to merge this PR into the master branch.

**Comment by mohanadarafe** [comment]
Due to the large number of binary files, we will keep SonarQube in your branch for testing.

**Pull request closed without merging**
